### ISSUE TITLE
IG-88A/B/C/D need to clean up their pilot abilities when they die

### ISSUE THREAD

**Issue by Sleet01** [xws-bench/bench#13]
Currently, if one of IG-88 ships with the IG-2000 title is destroyed, the other ship keeps the destroyed ship's pilot ability as well as its own.

[See this graphic](https://s3-us-west-2.amazonaws.com/xwing/XWS-bench_bugs/xws-bench-d59d8001eb21a9a821f8a2699a30b5040cc69489-bug-IG88-title.png) showing IG-88C using the destroyed IG-88B's 2nd attack ability.

Expected: IG-2000 should not grant the pilot skill of a destroyed IG-88 pilot to remaining pilot(s).

Actual: Dat mutafukah!

Note: If XWS-bench supports / will later support Epic or > 100-point games, the cleanup method should remove the relevant pilot ability from all other IG-88s, not just one other, in case there are more than 2 total.

**Comment by xws-bench** [comment]
Yes, done. Desactivation is global. When initializing a special capacity, the unit knows the source of this effect (which unit capacity it is). The capacity is only active when the source is not dead.
Actually, there is no limitation on the squad points you use, so you can already play with many IG-88s.

**Comment by Sleet01** [comment]
Nice work!  Verified fixed as of 4557ecd433045840854ba549efe4612bd3b7bbb8.  Closing.
