### ISSUE TITLE
Y-Wing Title/R3-A2 Firing Issue

### ISSUE THREAD

**Issue by SneakyPetes** [xws-bench/bench#20]
Using a Y-Wing with the BTLA4 title and R3-A2--the option to use the droid comes up, but doesn't give an actual option to shoot.  Then it gives you the option to keep doing this endlessly.  Have to hit "next" to end turn in order to continue.

**Comment by TNG-Wing** [comment]
I have had the same problem. Both as player and with the AI. Would love to set this fixed!  Thanks!

**Comment by xws-bench** [comment]
Ok, this should be better now, you can fire with the Y-Wing ! Cheers !

**Comment by TNG-Wing** [comment]
Thanks again! Amazed by your quick response!  😆
