### ISSUE TITLE
Game Set Up: Ships off board, no rocks, ship info not present

### ISSUE THREAD

**Issue by SneakyPetes** [xws-bench/bench#21]
So, basically, can't use program right now.

**Comment by SneakyPetes** [comment]
![screen shot 2017-04-06 at 9 49 00 pm](https://cloud.githubusercontent.com/assets/26988977/24782258/ff882906-1b12-11e7-9113-81ddf5309e54.png)

**Comment by Mitchal** [comment]
It seems a lot of the issues created the last 24 hours are really duplicates, so I won't create another one. I will, however, add my observations:

1. The error output in the console is the following: 
```
Uncaught TypeError: this.wrap_after is not a function
    at Weapon.init (all.min.js:952)
    at Team.tosquadron (all.min.js:1173)
    at Team.endselection (all.min.js:1174)
    at setphase (all.min.js:1276)
    at nextphase (all.min.js:1271)
    at HTMLLIElement.onclick (VM247 main.html:309)
init @ all.min.js:952
tosquadron @ all.min.js:1173
endselection @ all.min.js:1174
setphase @ all.min.js:1276
nextphase @ all.min.js:1271
onclick @ VM247 main.html:309
```
2. A very simple squad to use to be able to reproduce this is for example:
```
Contracted Scout + Proton Torpedoes
```
Without the torpedoes, it works. With it, it does not. 

I'm sure this is enough info to fix the problem.

Thanks for a fun tool :-) 

Cheers!

**Comment by xws-bench** [comment]
Yes, nasty bug due to some recent modification, affecting plenty of upgrades/pilots. Corrected !
Cheers !
