### ISSUE TITLE
Placement error on setup

### ISSUE THREAD

**Issue by gmodos** [xws-bench/bench#24]
If I wanted to benchmark two random squad, I got the attached setup screen.
For example:
Zeb Orrelios(Attack Shuttle) + Chopper + Phantom
Biggs Darklighter + M9-G8 + Integrated Astromech
Kanan Jarrus + Fire-Control System + Twin Laser Turret + Rey + Finn + Tactical Jammer + Ghost
VS.
Captain Yorr + Collision Detector + Kylo Ren + Darth Vader
Lieutenant Dormitz + Fire-Control System + Tactical Jammer
Major Stridan + Fire-Control System + Inspiring Recruit + Tactical Jammer
![sb_error](https://cloud.githubusercontent.com/assets/12628798/24797883/96788010-1b93-11e7-946e-40389930fdf9.png)

**Comment by echoesandechoes** [comment]
I can't figure out the exact issue, but I'm having trouble with the Upsilon Shuttle as well: either the game starts up like your image and/or it won't progress to Turn 1.

**Comment by xws-bench** [comment]
Yes, solved ! There was a bug relative to some upgrades.
