### ISSUE TITLE
Biggs Darklighter

### ISSUE THREAD

**Issue by russbean** [xws-bench/bench#34]
I'm having trouble using Biggs in a list.  If he is in any list, even one where is is alone, the list won't load for setup.  I have been using Chrome, but I tried this in IE and Edge as well.

It looks like I can't select Biggs on the build screen either.

**Comment by russbean** [comment]
This issue appears to be fixed.  Thank you.

**Comment by xws-bench** [comment]
Well, I was unsure, but finally yes.
