### ISSUE TITLE
Missiles/Torpedoes + Guidance Chip

### ISSUE THREAD

**Issue by Psychoholyk** [xws-bench/bench#35]
Hi, 

There seem to be a problem with Missiles and Torpedoes with Guidance Chip.

A ship equipped with both get stuck in the top-left corner with the game kinda freezing.
I tried it with Scum Z's and Rebel E's
It seems ok if the ship(s) are only equipped with one or the other upgrade.

Keep up the good work, thanks!

**Comment by xws-bench** [comment]
Corrected ! Nasty bug for some upgrades. Cheers !
