### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by lioga69** [xws-bench/bench#36]
When i creat a squad in french, all is fine until i return on the combat screen where you see 2 windows 1 et 2. At this moment the squad built previously appears with the wrong amount point. If i make a copy and past it works....

https://xws-bench.github.io/bench/main.html#selectphase

**Comment by lioga69** [comment]
Dash Rendar, Lone wolf, outrider, HLC, recon specialist. 

Wrong amount point after building. Ok during building phase.

**Comment by xws-bench** [comment]
Yes, there was something wrong in the storage of squads, due to the language. Thanks I have corrected this.
