### ISSUE TITLE
Benchmark bugs - Aggressor Cannons and Biggs Darklighter

### ISSUE THREAD

**Issue by rowansweee** [xws-bench/bench#39]
Hi, Great program, I really enjoy using it, but I wanted to report a bug in the newest version - when building squads with the Scum Ship Aggressor, if a cannon is selected, once entering the battle screen, the app will hang, and no further happens.

This also happens when squads are selected with Biggs Darklighter, this is less of a problem, because in the squad builder program, he can't even be selected, but if you import a squad, the problem happens as described above.

Cheers, and keep up the good work!

**Comment by xws-bench** [comment]
Ok, this seems to work again. Tell me if it's not the case for you.
Cheers !
