### ISSUE TITLE
No fire button

### ISSUE THREAD

**Issue by TNG-Wing** [xws-bench/bench#47]
There is no fire button anymore. Can't attack/play.

Thanks!

**Comment by xws-bench** [comment]
Ok, with which squad ? I've just tested it with a tournament squad and it fires. Cheers !

**Comment by xws-bench** [comment]
Ok, found it, cleaning the code yesterday introduced this bug, sorry ! Cheers!

**Comment by TNG-Wing** [comment]
Thank you, it was a custom list with Biggs Lothal Rebel and Zeb
