### ISSUE TITLE
Fire button not always coming up

### ISSUE THREAD

**Issue by devonjones** [xws-bench/bench#5]
I did a battle where squad 2 was a set of 3 jumpmaster 5ks.  most of the time their attacks failed to operate, because it was rolling the dice, but not giving me a fire button to press.  The only way to move forward was then to hit next, which meant most of their attacks failed to go off.

**Comment by xws-bench** [comment]
Hmmm, it was 8 days ago, and R4 was not working well with AI. Was it the case ? 
Otherwise, in case of such bug, open the javascript console and post the errors you can find, I'll locate the errors.

**Comment by devonjones** [comment]
Yeah, that's probably the right timing.  I'll give it a spin with the list where I saw the issue.
