### ISSUE TITLE
Allow Importing of Lists

### ISSUE THREAD

**Issue by ajmath** [xws-bench/bench#6]
It's very time-consuming having to rebuild my lists using the app when they already exist on my phone and/or in other apps.  We should add an option to import via XWS format or another text-based format.  I've tried editing the squad text area but I'm unable to proceed once I've done this.

**Comment by Hinny** [comment]
It is already possible to import using xws or pure text. Just copy the xws and paste it in the squad window. Be aware that some cards will differ from the squad builders (Adaptability from Yet another Squadron builder wont work for instance) so it is not 100%.
You can also clone a squad to another device by copying the text in the squad text area save the text in an area you can reach with your other device, then copy and paste the text using your other device.

**Comment by xws-bench** [comment]
I think this issue is closed.
